### PR TITLE
Added Guides button.

### PR DESCRIPTION
**Pull request by Unease**
Added a guides button for future use.

### CODE REVIEW

**Review by PancakeTAS — APPROVED** [review]
Looks good.

**Comment by ScribbleTAS** [comment]
But isn't guides the same as tutorials? I am confusion...

**Comment by Unease** [comment]
From the way the the website was structured, I assumed that the tutorials section (Since you included playback and non playback), would be for explaining how to use the tools' basic functions. Similarly, I thought guides could be used for smaller stuff like a quickstart guide or some other things like how to put together a TAS (through the video editing process)

**Review by ScribbleTAS — APPROVED** [review]
Not 100% satisfied with the guide button, but it's ok

**Pull request merged**
